apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codecity
  namespace: codecity
  labels:
    app.kubernetes.io/name: codecity
  annotations:
    # Uncomment for nginx ingress controller
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
spec:
  ingressClassName: nginx
  rules:
    - host: codecity.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
